name: ActionsCI

env:
  Platform: #Any CPU|Win32|x64
  Configuration: Release
  Artifacts: build/Release/

on:
  push:
    branches: [master, develop]

jobs:
  build-windows-qt68:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.8.2
        host:         windows
        target:       desktop
        arch:       win64_mingw
        modules:      qtmultimedia
        setup-python: false
    - name: build
      shell: cmd
      run: |
       cmake -B./build -S. ${{ github.workspace }} \
          -DAPP_ARCHITECTURE=x64 \
          -DAPP_EXECUTABLE_FILENAME=${{ env.APP_EXECUTABLE_FILENAME }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_PREFIX_PATH=${{ env.Qt6_Dir }} -G "MinGW Makefiles"
        cmake --build ./build --config release
    - name: deploy
      run: windeployqt.exe build\Release\sans_titre.exe
    - name: Compress artifacts
      uses: vimtor/action-zip@v1.1
      with:
        files: build\Release
        dest: "build/sans_titre.zip"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sans_titre.zip
        path: build\Release
