name: ActionsCI

env:
  Platform: #Any CPU|Win32|x64
  Configuration: Release
  Artifacts: build/Release/

on:
  push:
    branches: [master, develop]

jobs:
  build-windows-qt68:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.8.2
        host:         windows
        target:       desktop
        arch:       win64_mingw
        modules:      qtmultimedia
        setup-python: false
    - name: build
      shell: cmd
      run: |
        cmake -B build -S . -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=$env:QTDIR  -DCMAKE_BUILD_TYPE=Release
        cd build
        ls
        mingw32-make -j16
    - name: deploy
      run: windeployqt.exe build\Release\sans_titre.exe
    - name: Compress artifacts
      uses: vimtor/action-zip@v1.1
      with:
        files: build\Release
        dest: "build/sans_titre.zip"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sans_titre.zip
        path: build\Release
