name: Build Qt 6 Program

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: 'C:/Qt'

    - name: Set up MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake

    - name: Add Qt and MinGW to PATH
      run: |
        echo "C:/Qt/6.2.0/mingw81_64/bin" >> $GITHUB_PATH
        echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        mingw32-make
